# Generated by Django 4.1.1 on 2023-08-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.CharField(blank=True, max_length=200, null=True)),
                ('localidad', models.CharField(blank=True, max_length=200, null=True)),
                ('latitud', models.CharField(blank=True, max_length=200, null=True)),
                ('longitud', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
